name: Build & Test Lean

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: quantconnect/lean:foundation
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.Lean.sln
